name: Compilar Ejecutable Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.x'  # Usar Python 3.8
          architecture: x64

      - name: Configurar entorno virtual
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          .\venv\Scripts\python.exe -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compilar con PyInstaller
        run: |
          .\venv\Scripts\activate
          pyinstaller --onefile --windowed --add-data "chromedriver.exe;." ExtractorBecas.py

      - name: Subir ejecutable como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Ejecutable-Windows
          path: dist/ExtractorBecas.exe
